blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/ajay-bhargava/poetry-cookiecutter/pulls
    about: Please direct your awe and inquiries to Ajay via a PR. Lets build, not discuss. 