name: ðŸ“‡ Make a Repository Customization
description: This is an issue template that allows you to choose how you want your desired Repository to appear.
title: Enter a short description of what this repository is supposed to do. 
body:
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: What is the github email of the person who will be responsible for this repository?
    placeholder: ex. email@example.com
- type: markdown
  attributes:
    value: |
      ## Introduction
      Please select one of the types of Repository you would like to create.

      ## :warning: Defaults
      The default option is Package Repository.

      ## Choices
      | No. | Category | Item | Jupyter | Additional Info |
      |-----|----------|------|---------|-------|
      | 1   | Python   | Package Repository        | :x: | `typer` is enabled by default with ability to push to PyPi |
      | 2   | Python   | Pydantic Repository       | :x: | `mypy` Pydantic model checking is enabled by default with ability to push to PyPi |
      | 3   | Streamlit| Streamlit Repository      | :x: | `streamlit` is enabled by default and ability to push to ECR is enabled |
      | 4   | FastAPI  | FastAPI                   | :white_check_mark: | `fastapi` is enabled by default, with ability to push repo to ECR provided variables are supplied |
      | 5   | FastAPI  | FastAPI with ML           | :white_check_mark: | `fastapi` is enabled by default, with ability to deploy a novel model from a foundation repository like [ðŸ¤—](huggingface.co) to FastAPI endpoint from AWS API Gateway + AWS Î» |
      | 6   | FastAPI  | FastAPI with ML Training  | :white_check_mark: | `fastapi` is enabled by default, with ability to train the model. Data versioning is enabled via `DVC` and remote is configured. There is further ability to create FastAPI endpoint from AWS API Gateway + AWS Î»  |

- type: dropdown
  id: python
  attributes:
    label: Python Repository
    multiple: false
    options:
      - 1-Package Repository
      - 2-Pydantic Repository

- type: dropdown
  id: streamlit
  attributes:
    label: Streamlit Repository
    multiple: false
    options:
      - 3-Streamlit Repository

- type: dropdown
  id: fastapi
  attributes:
    label: FastAPI Repository
    multiple: false
    options:
      - 4-FastAPI
      - 5-FastAPI with ML
      - 6-FastAPI with ML Training