name: Setup Repository
on: 
    workflow_dispatch:

jobs:
    check_if_template_repository:
        name: Check if template repository.
        runs-on: ubuntu-latest
        steps:
            - name: Generate App Token
              uses: tibdex/github-app-token@v2
              id: token
              with:
                app_id: ${{ vars.APP_ID}}
                private_key: ${{ secrets.APP_PEM_PRIVATE_KEY}}
            
            - name: Check if template repository
              shell: bash
              id: github_api
              env:
                APP_TOKEN: ${{ steps.token.outputs.token }}
              run: |
                RESPONSE=$(curl -L --silent \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $PAT_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/$GITHUB_REPOSITORY)

                echo "REPOSITORY_ID=$(echo $RESPONSE | jq -r ".id")" >> $GITHUB_OUTPUT
                echo "EXIT_STATUS=$(echo $RESPONSE | jq -r ".is_template")" >> $GITHUB_OUTPUT
        outputs:
          repository_id: ${{ steps.github_api.outputs.REPOSITORY_ID }}
          is_template: ${{ steps.github_api.outputs.EXIT_STATUS }}

    # setup_repository:
    #     name: Setup Repository
    #     runs-on: ubuntu-latest
    #     needs: check_if_template_repository
    #     if: |
    #       needs.check_if_template_repository.outputs.is_template == 'true'
    #     permissions:
    #         id-token: write
    #         contents: write
    #     steps:
    #         - name: Checkout Repository
    #           uses: actions/checkout@v4
    #           with:
    #             path: template
            
    #         - name: Setup Python
    #           uses: actions/setup-python@v4
    #           with:
    #             python-version: 3.10

    #         - name: Install Cruft and Apply Issue Choice
    #           env: 
    #             REPOSITORY_ID: ${{ needs.check_if_template_repository.outputs.repository_id }}
    #           run: |
    #             pip install --no-input cruft
    #             cruft create --no-input --extra-context '{"github_repository_id": "${REPOSITORY_ID}"}' ./template
                

              
        
            




            
            
