name: Parse Issue

on:
  issues:
    types: opened

concurrency: 'main'

jobs:
  parse-issue:
    runs-on: ubuntu-latest
    permissions:
    id-token: write
    contents: write
    outputs:
      jsonString: ${{ steps.create-cruft-json.outputs.jsonString }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Create and activate a UV virtual environment (Unix)
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv venv .venv
        echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
        echo "$PWD/.venv/bin" >> $GITHUB_PATH

    - name: Install Typer and JSON
      run: |
        uv pip install typer json
    
    - name: Parse Issue
      uses: stefanbuck/github-issue-parser@v3
      id: issue-parser
      with:
        template-path: .github/ISSUE_TEMPLATE/setup-repository.yml

    - name: Create setup.json
      run: echo '${{ steps.issue-parser.outputs.jsonString }}' > setup.json

    # - name: Create Cruft JSON File
    #   id: create-cruft-json
    #   run: |
    #     python3 parse.py find-number setup.json
    
    - name: Close Issue
      if: ${{ steps.issue-parser.outputs.jsonString != null }}
      uses: peter-evans/close-issue@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        comment: 'Issue #${{ github.event.issue.number }} We will now proceed to setup your repository.'

      