name: Issue Parsing Test
on:
  pull_request:
    branches:
     - main
jobs:
  test_issue_parsing:
    name: Test Issue Parsing Scripting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          installer-parallel: true
          virtualenvs-create: true
          virtualenvs-in-project: true
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: poetry
      
      - name: Install Poetry Project
        run: |
          poetry env use 3.11
          poetry install --no-interaction

      - name: Run Issue Parsing Tests
        run: |
          poetry run pytest
      
        
      
  